name: Python CI

# Trigger the workflow on every push to the repository
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]  # Make sure this matches the Python version you're using

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        
    - name: Lint with flake8
      run: |
        # Run flake8 and stop the build if errors are found
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run tests with pytest
      run: |
        pytest  # Run all pytest tests in the repository
